config/routes.rb
Rails.application.routes.draw do
  resources :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:edit, :show, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    return render :new unless @entry.save
    redirect_to @entry, notice: 'Entry creation succeeded.'
  end

  def update
    return render :edit unless @entry.update(entry_params)
    redirect_to @entry, notice: 'Entry update succeeded.'
  end

  def destroy
    @entry.destroy!
    redirect_to entries_path
  end

  private
  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(
        :title,
        :body
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_flash.html.haml
- if flash[:notice].present?
  %p.notice= flash[:notice]

app/views/entries/_form.html.haml
= render partial: 'flash', locals: {flash: flash}

- if entry.errors.any?
  .errors
    %p
      %strong= "#{entry.errors.count} input errors"
    - entry.errors.full_messages.each do |error_message|
      %ul
        %li= error_message

= form_for(entry) do |entry_form|
  %table
    %tr
      %th Title
      %td= entry_form.text_field :title
    %tr
      %th Body
      %td= entry_form.text_area :body

  %nav.actions
    %ul
      %li= entry_form.submit 'Save'
      %li= link_to 'Index', entries_path

app/views/entries/edit.html.haml
%h1 Entries#edit

= render partial: 'form', locals: {entry: @entry}

app/views/entries/index.html.haml
%h1 Entries#index
%table
  %thead
    %tr
      %th Title
      %th Body
      %th &nbsp;
      %th &nbsp;
      %th &nbsp;
  %tbody
    - @entries.each do |entry|
      %tr
        %td= entry.title
        %td= entry.body
        %td= link_to 'Show', entry
        %td= link_to 'Edit', edit_entry_path(entry)
        %td= link_to 'Destroy', entry, method: :delete, data: {confirm: 'are you delete?'}
%nav.links
  %ul
    %li= link_to 'New', new_entry_path

app/views/entries/new.html.haml
%h1 Entries#new
= render partial: 'form', locals: {entry: @entry}

app/views/entries/show.html.haml
%h1 Entries#show
= render partial: 'flash', locals: {flash: flash}
%table
  %tr
    %th Title
    %td= @entry.title
  %tr
    %th Body
    %td= @entry.body
%nav.links
  %ul
    %li= link_to 'Edit', edit_entry_path(@entry)
    %li= link_to 'Index', entries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAssignmentCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= yield %>
    </div>
  </body>
</html>